### ISSUE TITLE
config files get mounted as directory by the installer

### ISSUE THREAD

**Issue by ram4ibm** [carrier-io/installer#7]
Hi,

First of all, this is a very good tool and definitely should be supported in K8S. I am happy to contribute if you have any other repo for K8S installation. 

Before that, I am trying carrier to install on Amazon Linux. The install script and the container installer are bit flaky and I am not able to identify what the config mismatches are..

`[root@ip-172-31-12-137 dev]# dcu
Creating network "dev_default" with the default driver
Creating carrier-traefic     ... done
Creating carrier-redis    ... done
Creating carrier-minio       ... done
Creating carrier-postgres    ... done
Creating carrier-influx      ... done
Creating observer-hub        ... done
Creating carrier-loki        ... done
Creating dev_jenkins_1       ... done
Creating carrier-interceptor ... done
Creating carrier-grafana     ... done
Creating carrier-keycloak    ... done
Creating carrier-vault       ... done
Creating carrier-galloper    ... done
Creating carrier-auth        ... done
[root@ip-172-31-12-137 dev]# dps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                           PORTS                                            NAMES
3c7aed574ca7        getcarrier/carrier-auth:latest             "app"                    6 seconds ago       Up 2 seconds                                                                      carrier-auth
ca4ff434aee7        getcarrier/galloper:latest                 "/tmp/start.sh"          7 seconds ago       Up 4 seconds                     5000/tcp                                         carrier-galloper
0438823ffc82        jboss/keycloak:9.0.0                       "/opt/jboss/tools/do…"   10 seconds ago      Up 6 seconds                     8080/tcp, 8443/tcp                               carrier-keycloak
4b477af00ff4        vault:latest                               "docker-entrypoint.s…"   10 seconds ago      Up Less than a second            8200/tcp                                         carrier-vault
2ee8f6c0b397        grafana/grafana:6.4.4                      "/run.sh"                12 seconds ago      Up 9 seconds                     3000/tcp                                         carrier-grafana
dd3bbcfc7b43        getcarrier/interceptor:latest              "/tmp/start.sh"          14 seconds ago      Restarting (1) 2 seconds ago                                                      carrier-interceptor
d9f3a761558c        grafana/loki:latest                        "/usr/bin/loki -conf…"   16 seconds ago      Up 11 seconds                    0.0.0.0:3100->3100/tcp                           carrier-loki
f7cfe98856c6        getcarrier/observer-hub:latest             "app"                    16 seconds ago      Up 10 seconds                    0.0.0.0:4444->4444/tcp                           observer-hub
b73d002f45e3        jenkins/jenkins:lts                        "/sbin/tini -- /usr/…"   16 seconds ago      Up 10 seconds                    8080/tcp, 0.0.0.0:50000->50000/tcp               dev_jenkins_1
5cada0062d97        influxdb:1.7                               "/entrypoint.sh infl…"   16 seconds ago      Up 12 seconds                    0.0.0.0:2003->2003/tcp, 0.0.0.0:8086->8086/tcp   carrier-influx
3f327a2c291d        postgres:12.2                              "docker-entrypoint.s…"   16 seconds ago      Restarting (126) 2 seconds ago                                                    carrier-postgres
c8cff2c7327d        minio/minio:RELEASE.2019-10-12T01-39-57Z   "/usr/bin/docker-ent…"   16 seconds ago      Up 13 seconds                    9000/tcp                                         carrier-minio
ee023f9d390e        redis:5.0.7                                "redis-server --requ…"   16 seconds ago      Up 14 seconds                    0.0.0.0:6379->6379/tcp                           carrier-redis
72121ae2a786        traefik:cantal                             "/entrypoint.sh trae…"   16 seconds ago      Restarting (1) 4 seconds ago                                                      carrier-traefic
[root@ip-172-31-12-137 dev]# klp 721
2020/08/21 07:17:02 command traefik error: read /etc/traefik/traefik.toml: is a directory
2020/08/21 07:17:06 command traefik error: read /etc/traefik/traefik.toml: is a directory
2020/08/21 07:17:12 command traefik error: read /etc/traefik/traefik.toml: is a directory
2020/08/21 07:17:16 command traefik error: read /etc/traefik/traefik.toml: is a directory
2020/08/21 07:17:21 command traefik error: read /etc/traefik/traefik.toml: is a directory
2020/08/21 07:17:26 command traefik error: read /etc/traefik/traefik.toml: is a directory
`

This is not happening always. On some directories, if I manually create directory, clone the repo and start them from docker-compose up -d them from beginning it works. But the realm auth config is not complete.

But me and my friend have been struggling to get this work for the past 3 weeks.

**Comment by arozumenko** [comment]
Hi @ram4ibm 
Could you please describe the steps you are following?

in case you are doing thing from /dev folder with docker-compose, you'd like to pay attention to https://github.com/carrier-io/carrier-io/blob/master/InstallationWithSSL.md 

as /dev folder (according to docker-compose output) actually now default to specific installation scenario with HTTPS enabled by default

**Comment by ram4ibm** [comment]
Hi @arozumenko ,

Thanks for a swift reply. I have done the following

1. Brought up a 16G RAM Amazon Linux
2. Installed docker in it
3. Cloned your git repo
4. cd dev
5. vi .env
# General section
APP_HOST=http://<Resolvable Domain Name>
APP_DOMAIN=localhost
CARRIER_PATH=/opt/carrier
6. docker-compose up -d

Also, I tried your installer container to get the local install. The following steps do not work on Amazon Linux. Please confirm, I will shift to ubuntu, not a bog deal 

Local installation:
Run the docker command: docker run -it -v /opt:/opt -v /var/run/docker.sock:/var/run/docker.sock -p 1337:1337 getcarrier/installer

Open http://localhost:1337/ in your browser

Choose local

I faced this error
`root@ip-172-31-12-137 dev]# docker run -it -v /data/carrier:/opt -v /var/run/docker.sock:/var/run/docker.sock -p 9999:1337 getcarrier/installer
Unable to find image 'getcarrier/installer:latest' locally
latest: Pulling from getcarrier/installer
7595c8c21622: Pull complete 
d13af8ca898f: Pull complete 
70799171ddba: Pull complete 
b6c12202c5ef: Pull complete 
3c5039246f3f: Pull complete 
ea4546edc53c: Pull complete 
edb177e22a21: Pull complete 
b8dc883bbfda: Pull complete 
Digest: sha256:cae4894a6e98edb0c02e005f175354dbafdb8bac8df297ef8d6ee8429fec13ec
Status: Downloaded newer image for getcarrier/installer:latest
 * Serving Flask app "installer" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:1337/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 253-791-811
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET / HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/css/style.css HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/js/jquery.slim.min.js HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/js/popper.min.js HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/img/cloud.png HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/img/ssh.png HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/img/local.png HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/img/bg-logo.jpg HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:50] "GET /static/img/kuber.png HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:34:51] "GET /favicon.ico HTTP/1.1" 404 -
2.126.193.192 - - [21/Aug/2020 06:34:57] "GET /local HTTP/1.1" 200 -
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [127.0.0.1] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Prepare folders] **********************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Install aptitude using apt] ***********************************************************************************************************************************************************************************************************
[WARNING]: Updating cache and auto-installing missing dependency: python-apt

changed: [127.0.0.1]

TASK [Install required system packages] *****************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => (item=apt-transport-https)
changed: [127.0.0.1] => (item=git)
ok: [127.0.0.1] => (item=ca-certificates)
changed: [127.0.0.1] => (item=curl)
changed: [127.0.0.1] => (item=software-properties-common)

TASK [Install required system packages] *****************************************************************************************************************************************************************************************************
skipping: [127.0.0.1] => (item=epel-release) 
skipping: [127.0.0.1] => (item=yum-utils) 
skipping: [127.0.0.1] => (item=lvm2) 
skipping: [127.0.0.1] => (item=git) 
skipping: [127.0.0.1] => (item=ca-certificates) 
skipping: [127.0.0.1] => (item=curl) 

TASK [Install docker-compose] ***************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Install docker-compose] ***************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [git] **********************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Remove unimportant files] *************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Replace App Host] *********************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Replace install path] *****************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Create and start services] ************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Create and start services] ************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [Wait until the services fully load] ***************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Copy files] ***************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [bootstrap] ****************************************************************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "bash /opt/carrier/dev/bootstrap.sh", "delta": "0:01:58.713544", "end": "2020-08-21 06:40:05.315360", "msg": "non-zero return code", "rc": 7, "start": "2020-08-21 06:38:06.601816", "stderr": "Logging into http://localhost:8080/auth as user carrier of realm master\nFailed to send request - Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "stderr_lines": ["Logging into http://localhost:8080/auth as user carrier of realm master", "Failed to send request - Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused", "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused"], "stdout": "", "stdout_lines": []}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=12   changed=11   unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   

/usr/local/lib/python3.6/dist-packages/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
  BrokenFilesystemWarning,
2.126.193.192 - - [21/Aug/2020 06:40:05] "POST /local HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2.126.193.192 - - [21/Aug/2020 06:40:05] "GET /local?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:40:05] "GET /local?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:40:05] "GET /local?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:40:05] "GET /local?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:40:06] "GET /local?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2.126.193.192 - - [21/Aug/2020 06:40:06] "GET /local?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
`
